### ISSUE TITLE
Sign In / Register UI

### ISSUE THREAD

**Issue by baoquandinh** [Here2Huynh/Face-Recognition#4]
UI should hide when user is on that specific page.
Example:
Sign In page should not have the "Sign In" option on the upper right-hand side.

**Comment by Here2Huynh** [comment]
Great idea for better UX! Implemented in this pull request, please approve it: 
https://github.com/Here2Huynh/Face-Recognition/pull/6

**Comment by Here2Huynh** [comment]
https://github.com/Here2Huynh/Face-Recognition/pull/7 Approve this one for merge to master.
